In [1]:
import numpy as np

In [4]:
# create array with arange  fuction of numpy

a = np.arange(15) # its mean less than 15 no. we find in the our matrix

a = np.arange(15).reshape(3,5) # so we have 3 row and 5 column

In [5]:
print(a)

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]]


In [7]:
# size of array
a.size

# dimensions of array
a.ndim

# datatype of array
a.dtype

dtype('int64')

In [9]:
# creating array from the iterator
list_b = [0,1,2,3,4,5,6,7,8]

b = np.array(list_b).reshape(3,3)
print(b)

[[0 1 2]
 [3 4 5]
 [6 7 8]]


In [16]:
# creating multi- dimension array from a iterator
b = np.array([(1.5 ,2, 3),(5, 6, 7)])
print(b)

[[1.5 2.  3. ]
 [5.  6.  7. ]]


In [19]:
# dtype(data type) can also be specified
c = np.array([[1,2], [3,4]], dtype= complex)
print(c)

[[1.+0.j 2.+0.j]
 [3.+0.j 4.+0.j]]


In [21]:
# array of zeros
zeros = np.zeros((3,4))

print(zeros)

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]


In [23]:
# array of ones
ones = np.ones((2,3,4), dtype=np.int16)

print(ones)

[[[1 1 1 1]
  [1 1 1 1]
  [1 1 1 1]]

 [[1 1 1 1]
  [1 1 1 1]
  [1 1 1 1]]]
