In [1]:
import numpy as np

In [4]:
# create array with arange  fuction of numpy

a = np.arange(15) # its mean less than 15 no. we find in the our matrix

a = np.arange(15).reshape(3,5) # so we have 3 row and 5 column

In [5]:
print(a)

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]]


In [7]:
# size of array
a.size

# dimensions of array
a.ndim

# datatype of array
a.dtype

dtype('int64')

In [9]:
# creating array from the iterator
list_b = [0,1,2,3,4,5,6,7,8]

b = np.array(list_b).reshape(3,3)
print(b)

[[0 1 2]
 [3 4 5]
 [6 7 8]]


In [16]:
# creating multi- dimension array from a iterator
b = np.array([(1.5 ,2, 3),(5, 6, 7)])
print(b)

[[1.5 2.  3. ]
 [5.  6.  7. ]]


In [19]:
# dtype(data type) can also be specified
c = np.array([[1,2], [3,4]], dtype= complex)
print(c)

[[1.+0.j 2.+0.j]
 [3.+0.j 4.+0.j]]


In [21]:
# array of zeros
zeros = np.zeros((3,4))

print(zeros)

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]


In [23]:
# array of ones
ones = np.ones((2,3,4), dtype=np.int16)

print(ones)

[[[1 1 1 1]
  [1 1 1 1]
  [1 1 1 1]]

 [[1 1 1 1]
  [1 1 1 1]
  [1 1 1 1]]]


# MCQ  test question

In [8]:
class A:
    def __init__(self,b):
        self.b=b
    def display(self):
        print(self.b)
obj=A("Hello")
del obj

In [34]:
class B(object):
    def first(self):
        print("first method called")
    def second():
        print("second method called")
ob = B()
B.first(ob)

first method called


In [10]:
class change:
    def __init__(self,x,y,z):
        self.a= x + y + z

x = change(1,2,3)
y = getattr(x,"a")
setattr(x,'a',y+1)
print(x.a)

7


In [12]:
class fruits:
    def __init__(self,price):
        self.price = price
obj = fruits(50)

obj.quantity=10
obj.bags=2

print(obj.quantity+len(obj.__dict__))

13


In [13]:
class Demo:
    def __init__(self):
        pass

    def test(self):
        print(__name__)

obj = Demo()
obj.test()

__main__


In [14]:
class demo():
    def __repr__(self):
        return '__repr__built-in function called'
    def __str__(self):
        return '__str__built-in function called'

s=demo()
print(s)

__str__built-in function called


In [16]:
class stud:
    def __init__(self,roll_no, grade):
        self.roll_no = roll_no
        self.grade = grade
    def display(self):
        print("Roll no :", self.roll_no, "Grade :", self.grade)
stud1 =stud(34,'S')
stud1.age=7
print(hasattr(stud1,'age'))

True


In [17]:
def func(a, b=5,c=10):
    print('a is',a,'and b is', b,'and c is', c)

func(3,7)
func(25,c=24)
func(c=50,a=100)

a is 3 and b is 7 and c is 10
a is 25 and b is 5 and c is 24
a is 100 and b is 5 and c is 50


In [18]:
class Employee:
    empid=0
    name=""
    def __init__(id,name):
        empid=id
        name=name

In [21]:
def pow(b , p):
    y = b ** p
    return y

def square(x):
    a = pow(x,2)
    return a

n = 5
result = square(n)
print(result)

25


In [22]:
def test(a,b=5):
    print(a,b)

test(-3)

-3 5


In [28]:
class test:
    def __init__(self):
        self.variable = 'Old'
        self.Change(self.variable)
    def Change(self, var):
        var = 'New'
obj=test()
print(obj.variable)

Old


In [30]:
i=0
def change(i):
    i=i+1
    return i
change(1)
print(i)

0


In [32]:
def sayHello():
    print('Hallo World!')
sayHello()
sayHello()

Hallo World!
Hallo World!
