In [1]:
import numpy as np # np is also numpy

In [3]:
# creation of numpy array

x = np.array ([1,2,3,4,5])
print(x)
print(type(x))  #ndarray

[1 2 3 4 5]
<class 'numpy.ndarray'>


In [5]:
# shape and size
print(x.size) # total no. of elements
print(x.shape) # dimension wise elements
print(x.ndim) # num of dimensions

5
(5,)
1


In [3]:
x2d = np.array([[1,2,3],[4,5,6]])
print(x2d)
# shape and size
print(x2d.size) # total no. of elements
print(x2d.shape) # dimension wise elements
print(x2d.ndim) # num of dimensions

[[1 2 3]
 [4 5 6]]
6
(2, 3)
2


In [13]:
x25 = np.random.randint(1,100,(5,5)) # there we always find no. between 1 to 100 
print(x25)

[[38 71 31 23 54]
 [35 92 36 51 31]
 [12 76 35 92 17]
 [11 67 36 46 72]
 [94 14  8 20 83]]


In [15]:
xseq1 = np.arange(1,101,4)
print(xseq1.size,"elements")
print("=>1D MATRIX")
print(xseq1)
print("=>1D MATRIX RESHAPED TO 2D")
print(xseq1.reshape(5,5))

25 elements
=>1D MATRIX
[ 1  5  9 13 17 21 25 29 33 37 41 45 49 53 57 61 65 69 73 77 81 85 89 93
 97]
=>1D MATRIX RESHAPED TO 2D
[[ 1  5  9 13 17]
 [21 25 29 33 37]
 [41 45 49 53 57]
 [61 65 69 73 77]
 [81 85 89 93 97]]


In [8]:
xseq2 = np.linspace(1, 101, 50) 
print(xseq2.size,"elements") 
print("=> 1D MATRIX")
print(xseq2)
print("=>1D MATRIX RESHAPED TO 2D")
print(xseq2.reshape(10,5))
print("=>1D MATRIX RESHAPED TO 3D")
print(xseq2.reshape(5,5,2))

50 elements
=> 1D MATRIX
[  1.           3.04081633   5.08163265   7.12244898   9.16326531
  11.20408163  13.24489796  15.28571429  17.32653061  19.36734694
  21.40816327  23.44897959  25.48979592  27.53061224  29.57142857
  31.6122449   33.65306122  35.69387755  37.73469388  39.7755102
  41.81632653  43.85714286  45.89795918  47.93877551  49.97959184
  52.02040816  54.06122449  56.10204082  58.14285714  60.18367347
  62.2244898   64.26530612  66.30612245  68.34693878  70.3877551
  72.42857143  74.46938776  76.51020408  78.55102041  80.59183673
  82.63265306  84.67346939  86.71428571  88.75510204  90.79591837
  92.83673469  94.87755102  96.91836735  98.95918367 101.        ]
=>1D MATRIX RESHAPED TO 2D
[[  1.           3.04081633   5.08163265   7.12244898   9.16326531]
 [ 11.20408163  13.24489796  15.28571429  17.32653061  19.36734694]
 [ 21.40816327  23.44897959  25.48979592  27.53061224  29.57142857]
 [ 31.6122449   33.65306122  35.69387755  37.73469388  39.7755102 ]
 [ 41.81632653  4

In [10]:
xseq2d = xseq2.reshape(10,5)
print(xseq2d)

[[  1.           3.04081633   5.08163265   7.12244898   9.16326531]
 [ 11.20408163  13.24489796  15.28571429  17.32653061  19.36734694]
 [ 21.40816327  23.44897959  25.48979592  27.53061224  29.57142857]
 [ 31.6122449   33.65306122  35.69387755  37.73469388  39.7755102 ]
 [ 41.81632653  43.85714286  45.89795918  47.93877551  49.97959184]
 [ 52.02040816  54.06122449  56.10204082  58.14285714  60.18367347]
 [ 62.2244898   64.26530612  66.30612245  68.34693878  70.3877551 ]
 [ 72.42857143  74.46938776  76.51020408  78.55102041  80.59183673]
 [ 82.63265306  84.67346939  86.71428571  88.75510204  90.79591837]
 [ 92.83673469  94.87755102  96.91836735  98.95918367 101.        ]]


In [16]:
np.ones((5,5), dtype='int')

array([[1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1]])

In [21]:
x25

array([[65, 87, 53, 56, 34],
       [43, 34, 68, 75, 11],
       [56, 86, 93, 41, 88],
       [75, 36, 18, 42, 57],
       [45, 60, 25, 25,  7]])

In [24]:
# first row
print(x25[0])

[65 87 53 56 34]


In [25]:
# last row
print(x25[-1])

[45 60 25 25  7]


In [26]:
# single element
print(x25[0,1]) # same as print(x25[0][1])

87


In [27]:
# 1st columns
print(x25[:, 0])

# 2nd columns
print(x25[: 1])

# last columns
print(x25[:, -1])

[65 43 56 75 45]
[[65 87 53 56 34]]
[34 11 88 57  7]


In [28]:
# column 0 and 1 index
print(x25[:, [0,1]])

[[65 87]
 [43 34]
 [56 86]
 [75 36]
 [45 60]]


In [29]:
# column 0,1,2 idxs
print(x25[:, [0,1,2]])
# same thing as above
print(x25[:, :3])

[[65 87 53]
 [43 34 68]
 [56 86 93]
 [75 36 18]
 [45 60 25]]
[[65 87 53]
 [43 34 68]
 [56 86 93]
 [75 36 18]
 [45 60 25]]


In [33]:
# filtering data without numpy boolean filter(bad idea)
for i in x25:
    for j in i:
        if j <= 20:
            print(j)

11
18
7


In [34]:
x25 <= 20 # boolean filter

array([[False, False, False, False, False],
       [False, False, False, False,  True],
       [False, False, False, False, False],
       [False, False,  True, False, False],
       [False, False, False, False,  True]])

In [35]:
x25[ x25 <= 20]

array([11, 18,  7])

In [36]:
x25[ x25 > 50]

array([65, 87, 53, 56, 68, 75, 56, 86, 93, 88, 75, 57, 60])

In [39]:
(x25 > 20) & (x25 < 70)

array([[ True, False,  True,  True,  True],
       [ True,  True,  True, False, False],
       [ True, False, False,  True, False],
       [False,  True, False,  True,  True],
       [ True,  True,  True,  True, False]])

In [40]:
x25[(x25 > 20) & (x25 < 70)]

array([65, 53, 56, 34, 43, 34, 68, 56, 41, 36, 42, 57, 45, 60, 25, 25])

In [42]:
np.append?

Signature: np.append(arr, values, axis=None)
Docstring:
Append values to the end of an array.

Parameters
----------
arr : array_like
    Values are appended to a copy of this array.
values : array_like
    These values are appended to a copy of `arr`.  It must be of the
    correct shape (the same shape as `arr`, excluding `axis`).  If
    `axis` is not specified, `values` can be any shape and will be
    flattened before use.
axis : int, optional
    The axis along which `values` are appended.  If `axis` is not
    given, both `arr` and `values` are flattened before use.

Returns
-------
append : ndarray
    A copy of `arr` with `values` appended to `axis`.  Note that
    `append` does not occur in-place: a new array is allocated and
    filled.  If `axis` is None, `out` is a flattened array.

See Also
--------
insert : Insert elements into an array.
delete : Delete elements from an array.

Examples
--------
>>> np.append([1, 2, 3], [[4, 5, 6], [7, 8, 9]])
array([1, 2, 3, ..., 7, 8, 

In [44]:
np.append(x25, [1,2,3,4,5]) # not as expected, but work

array([65, 87, 53, 56, 34, 43, 34, 68, 75, 11, 56, 86, 93, 41, 88, 75, 36,
       18, 42, 57, 45, 60, 25, 25,  7,  1,  2,  3,  4,  5])

In [47]:
np.append(x25, np.array([[1,2,3,4,5]]), axis = 0) # two square brakets means 2D array

array([[65, 87, 53, 56, 34],
       [43, 34, 68, 75, 11],
       [56, 86, 93, 41, 88],
       [75, 36, 18, 42, 57],
       [45, 60, 25, 25,  7],
       [ 1,  2,  3,  4,  5]])

In [48]:
a = np.random.randint(1,100, (3,2))
b = np.random.randint(1,100, (2,3))

In [49]:
print(a.shape)
print(b.shape)

(3, 2)
(2, 3)


# transpose matriix
* we can add another matrix to the previous matrix in horizontal or in vertical direction

In [53]:
a.T # same as a.Transpose

array([[16, 68, 42],
       [44, 86, 52]])

In [52]:
print(np.hstack((a,b.T))) # horizontal stacking

[[16 44 14 18]
 [68 86 71  1]
 [42 52 52 94]]


In [55]:
print(np.hstack((a.T,b)))

[[16 68 42 14 71 52]
 [44 86 52 18  1 94]]


In [57]:
# vertical stacking
print(np.vstack((a,b.T))) 
print(np.vstack((a.T,b)))

[[16 44]
 [68 86]
 [42 52]
 [14 18]
 [71  1]
 [52 94]]
[[16 68 42]
 [44 86 52]
 [14 71 52]
 [18  1 94]]


In [16]:
x=np.random.randint(1,10,(3,3)) # between 1 to 10 and 3x3 matrix
y=np.random.randint(1,10,(3,3)) 
print(x)
print()
print(y)

[[5 1 6]
 [7 7 6]
 [4 5 7]]

[[3 7 3]
 [1 4 6]
 [9 8 5]]


In [19]:
print("add")
print(x+y) # addition

print('\nsub')
print(x-y) # subtraction

print('\ndiv')
print(x/y) # divide

print('\nelements wise multiplication')
print(x*y) # element wise mulriplication

print('\nelement wise mod')
print(x % y) # element wise multiplication

add
[[ 8  8  9]
 [ 8 11 12]
 [13 13 12]]

sub
[[ 2 -6  3]
 [ 6  3  0]
 [-5 -3  2]]

div
[[1.66666667 0.14285714 2.        ]
 [7.         1.75       1.        ]
 [0.44444444 0.625      1.4       ]]

elements wise multiplication
[[15  7 18]
 [ 7 28 36]
 [36 40 35]]

element wise mod
[[2 1 0]
 [0 3 0]
 [4 5 2]]


In [20]:
print(x.dot(y)) # mat multiplication 
print()

[[ 70  87  51]
 [ 82 125  93]
 [ 80 104  77]]



In [21]:
x.sum() # sum of all values

48

In [22]:
x.sum(axis=0) #row wise sum

array([16, 13, 19])

In [14]:
print(x.mean()) # all
print(x.mean(axis=0)) # row
print(x.mean(axis=1)) # column

4.777777777777778
[3.66666667 4.33333333 6.33333333]
[7.66666667 1.66666667 5.        ]


In [15]:
print(x.max()) # max value
print(x.min()) # min value
print(x.argmax()) # index of max value
print(x.argmax()) # index of min value
print(x.flatten()[4]) # accessing the index value given by argmax()

9
1
1
1
2


In [16]:
np.median(x) # some function are called using np, if not available through the variable

5.0